const divisionData = [
  {
    divisionName: "1A",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 1,
    numPrizeMoney: 2,
    numAutoPromo: 0,
    numPlayoffPromo: 0,
    numPlayoffRelegate: 1,
    numAutoRelegate: 1,
    players: [
      'Gwafey',
      'Night',
      'TetrisTime',
      'Redshurt',
      'Nek0',
      'Cobra',
      'Blue Scuti',
      'Myles',
    ],
  },
  {
    divisionName: "1B",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 1,
    numPrizeMoney: 2,
    numAutoPromo: 0,
    numPlayoffPromo: 0,
    numPlayoffRelegate: 1,
    numAutoRelegate: 1,
    players: [
      'Huff',
      'Meme',
      'Sodium',
      'SV',
      'DanV',
      'Coal',
      'Chiller',
      'Masy',
    ],
  },

  {
    divisionName: "2A",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      'Hydrant',
      'TobiGH3',
      'Marq',
      'Smoljordan',
      'Somalian',
      'Duzy K',
    ],
  },
  {
    divisionName: "2B",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      'Akatu',
      'Peek',
      'Winter',
      'Doodle',
      'Salted Sofa',
      'Manta7',
    ],
  },

  {
    divisionName: "3A",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 0,
    numAutoPromo: 2,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      'Lapis Lazuli',
      'Scamper',
      'Unor1ginalname',
      'MLGCaptainVirgil',
      'Anpu',
      'Wide',
      'AvGeek',
      'Deewee',
      'SillyShark',
    ],
  },
  {
    divisionName: "3B",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 0,
    numAutoPromo: 2,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      'Falkite',
      'Draco',
      'ID Kirby',
      '20Dan03',
      'Phloxae',
      'Evesy',
      'DocPi',
      'NeutrisicAcid',
      'Cryticalapis',
    ],
  },

  {
    divisionName: "4A",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      'WDSubia',
      'MrFaq',
      'NotZempro',
      'DrKnockers',
      'Mari',
      'TeainRain',
      'Gresiu',
    ],
  },
  {
    divisionName: "4B",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      'Kyradev',
      'IanKeith',
      'Tyler',
      'Vance',
      'Kingsman',
      'Vlad',
      'SwedishChef',
    ],
  },

  {
    divisionName: "5A",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 0,
    numAutoRelegate: 1,
    players: [
      'Roncli',
      'Skiplogic',
      'Eradach',
      'Weston',
      'Roman',
      'Hecate',
      'Jati',
      'JediEvan',
    ],
  },
  {
    divisionName: "5B",
    competition: "ctl",
    oneMatchPerPair: true,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 0,
    numAutoRelegate: 1,
    players: [
      'Gravy',
      'Toka',
      'Ninja of Ninjas',
      'Grand Designs',
      'Shake',
      'Suds',
      'Guerrero',
      'ThreesTwos',
    ],
  },

  // END CTL
  // BEGIN GOLD

  {
    divisionName: "Gold 49",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "ETHANTHOUGHTS",
      "STOLENSHORTSWORD",
      "KANNPLAYSTETRIS",
      "MAEDHROS",
      "UNSKILL",
      "DANNYMAGE",
      "BMAC",
      "SNOWYTETRIS",
    ]
  },
  {
    divisionName: "Gold 50",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "LIPTONEQ",
      "RONCLI",
      "DOBRYCZLEK",
      "THISINTHAT",
      "MIKAWAY",
    ]
  },
  {
    divisionName: "Gold 51",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "BRIANTHEONE",
      "GAMERZ",
      "SUNX2D",
      "EZHEDEH",
      "MRSWARTT",
    ]
  },
  {
    divisionName: "Gold 52",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "KANNPLAYSTETRIS",
      "DOBRYCZLEK",
      "COVERDALES",
      "TACOMOM",
      "OMENVOIR",
      "M149",
    ]
  },
  {
    divisionName: "Gold 53",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "ELPAILTEM",
      "SUDS",
      "LIPTONEQ",
      "ETHANTHOUGHTS",
      "CY1ER",
      "MIKEFLO",
    ]
  },
  {
    divisionName: "Gold 54",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "BURRITODAD",
      "JURAVLJOV",
      "SNOWYTETRIS",
      "MIKAWAY",
      "BILLYMAC",
      "THISINTHAT",
    ]
  },

  // END GOLD
  // BEGIN SILVER

  {
    divisionName: "Silver 61",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "321MRHAATZ",
      "THISINTHAT",
      "KAT",
      "CY1ER",
      "BRIANTHEONE",
      "TREEPRIEST",
      "LOKENZE",
    ]
  },
  {
    divisionName: "Silver 62",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "ARBARO",
      "THATKIDKIM",
      "M149",
      "ZYILDRL",
      "ENSCALIGHT",
      "CY1ER",
    ]
  },
  {
    divisionName: "Silver 63",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
      "MARTS",
      "BLINGUS",
      "MIRRORRIKER",
      "MAYHOFFER",
      "TACOMOM",
    ]
  },
{
    divisionName: "Silver 64",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 1,
    numAutoRelegate: 0,
    players: [
        "MARTS",
        "VASCO",
        "TREEPRIEST",
        "TEMPHUIBIS",
        "TOMELLO",
        "THATKIDKIM",
    ]
  },

  // END SILVER
  // BEGIN BRONZE

  {
    divisionName: "Bronze 70",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 0,
    numAutoRelegate: 0,
    players: [
      "KALIMOTXO",
      "BLINGUS",
      "SEVENPAGEWILSON",
      "ABYSS",
      "MAYHOFFER",
      "LILIANA",
      "GILDEDLIZARD",
    ]
  },
  {
    divisionName: "Bronze 71",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 0,
    numAutoRelegate: 0,
    players: [
      "SUPERJAYCODER",
      "TEMPHUIBIS",
      "ROGUEPOTATO",
      "CROIOS",
      "JUST_WOBERT",
      "LILIANA",
      "ADAMIRISH",
    ]
  },
  {
    divisionName: "Bronze 72",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 0,
    numAutoPromo: 1,
    numPlayoffPromo: 1,
    numPlayoffRelegate: 0,
    numAutoRelegate: 0,
    players: [
      "KALIMOTXO",
      "GILDEDLIZARD",
      "MRSKUBADOO",
      "CHEFBOYARGEEBS",
      "LILIANA",
    ]
  },

  // END BRONZE
  // BEGIN BEGINNER

  {
    divisionName: "Oak 12",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 1,
    numAutoPromo: 0,
    numPlayoffPromo: 0,
    numPlayoffRelegate: 0,
    numAutoRelegate: 0,
    players: [
      "ART_VANDELAY",
      "BBOT",
      "T1NY",
      "TR3BAS",
    ]
  },
  {
    divisionName: "Oak 13",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 1,
    numAutoPromo: 0,
    numPlayoffPromo: 0,
    numPlayoffRelegate: 0,
    numAutoRelegate: 0,
    players: [
      "ERILIONESS",
      "WILLIECUBED",
      "TIFFYFLOWR",
      "MRSKUBADOO",
    ]
  },
  {
    divisionName: "Oak 14",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 1,
    numAutoPromo: 0,
    numPlayoffPromo: 0,
    numPlayoffRelegate: 0,
    numAutoRelegate: 0,
    players: [
      "ERILIONESS",
      "WILLIECUBED",
      "SEVENPAGEWILSON",
      "SUPERSTEP",
      "BBOT",
      "YAZEN",
    ]
  },

  {
    divisionName: "Elm 8",
    competition: "tnp",
    oneMatchPerPair: false,
    numWinner: 1,
    numAutoPromo: 0,
    numPlayoffPromo: 0,
    numPlayoffRelegate: 0,
    numAutoRelegate: 0,
    players: [
      "SUPERSTEP",
      "DEEPSHOCK",
      "GOTH WITCH",
      "ANNISHARK",
    ]
  },
];

const adminRole = [
  "gregboomcannon#0",
  "moodeuce#0",
  "kingsman36#0",
  "tugi#0",
  "notzempro#0",
  "pkric#0",
  "danvvv#0",
  "nikvo#0",
  "chobge#0",
  "chillalla#0",
  "richardwolfvi#0",
  "frenchiestfrie#0",
  "snowlilyx#0",
];

const restreamerRole = [
".charsiu.#0",
".hazelnutmilk.#0",
".yler#0",
"＊Chong#8809",
"🇦🇷Joacozep#0518",
"1231231234#1231",
"20dan03#0",
"321mrhaatz#0",
"7pagewilson#0",
"8mansion8#0",
"aanti#0",
"adamirish18#0",
"Adrena1in#3056",
"afmirror#0",
"agamescout#0",
"akatu#0",
"Akideemus#0151",
"AkumaLuxray#4503",
"AL#2371",
"alexthach#0",
"allenbot#0",
"Alphabeth#2194",
"anangryroro#0",
"angrytrashyperson#0",
"aptiz712#0",
"ash_#7897",
"asherfullback#0",
"augmenttheampwave#0",
"aur9#9999",
"avgeekw159#0",
"avriix#0",
"b0rkedbear#0",
"B14NK#3752",
"Bakadrian#0601",
"BeastinShen#4218",
"bendy1#0",
"Benfamir#6783",
"Benjy#5752",
"bergtroll#0",
"billymac_#0",
"birbwizard#0",
"blargmeister#0",
"Bowser Tb#2424",
"boppyreal#0",
"boxie3210#0",
"bunnyboing#0",
"burritodad#0",
"c-dubs#2871",
"Careless#3403",
"catsugiri#0",
"cchristm#0",
"CharlesSparkley#7969",
"ChefGobes#6796",
"chefboyargeebs#0",
"chillala#0",
"ChirpingMatt#0801",
"chobge#0",
"Chris_Moulistanos#3251",
"cmcajaba#0",
"cmg444\\#4652",
"coalbucket2#0",
"cobra6731#0",
"codecracker01#0",
"CombatSlayer#1987",
"coverdales4#0",
"cwiiis#0",
"cy1ersrc#0",
"danvvv#0",
"DavidMichaelJ#5419",
"deepshock#0",
"deewee7#0",
"dekk_cl#0",
"DerJockel#2282",
"dhks0915#7525",
"digginout#1394",
"DitShadows#3241",
"DivCaste#6595",
"Dobry_Czlowiek#6510",
"dobreee#0",
"docpi314#0",
"dogpt#0",
"doodle#3414",
"doom338#0133",
"Dorukkaptan95#0404",
"DrKn0ckers#9860",
"dylan297#0",
"eliwa#0",
"ElleryStacks#4747",
"elpailtem#0",
"Emptyeye#7326",
"enscalight#0",
"eri_lioness#0",
"EricICX#6985",
"ethan1405#0",
"evesy#1650",
"eve_d#0",
"falkite#0",
"Felinho#7580",
"Fidhapre#9453",
"firedox#0",
"Flashmonger#7095",
"foiledthrice#8009",
"Foryst#0131",
"frenchiestfrie#0",
"frodododo#0",
"gabrielbondon#0",
"gekki.jb#0",
"GeoWolf77#3075",
"gerhard_adler#8867",
"gildedlizard#0",
"GM Damian-GDudge#9821",
"Grand Designs#3638",
"gregboomcannon#0",
"gummithecat#6363",
"hai5772#0",
"Haven#0602",
".hazelnutmilk.#0",
"heist#0",
"Hepps#2169",
"homejacob#0",
"huffulufugus#0",
"hunn14#0",
"hydrantdude#0",
"ian.capalot#0008",
"Iceblade73#7051",
"Id_korone#1070",
"Insaniso#8478",
"Ipiecevibes#6809",
"ITGBalbar#2408",
"itzsharky#0",
"iuqe#0",
"jakeywinks#7806",
"Jakub#4491",
"jamestomas2#7742",
"japorto#5801",
"jati727#0",
"javantea#0",
"jayp33#6638",
"jedievan4#0",
"Johann#1501",
"Joshua L. Tolles#4111",
"Jounce#7391",
"jrgagne99#0",
"just_wobert#0",
"Justus#4320",
"KAINOS#8036",
"Kibi Byte#4065",
"King Choke(Klystyr)(UTC -5)#9595",
"kingsman36#0",
"Klystyr (UTC -6)#9595",
"Kofi#6820",
"kominestris#0",
"kooliooolio#1009",
"Krypto#4388",
"KunfusingPoke#6098",
"kyira#0",
"lame mii#2430",
"lanheg#0",
"Lastarot#9931",
"leaurax#0455",
"lia_fr0st#0",
"lilian7774#0",
"liolio1230#9656",
"liptoneq196#0",
"Lord NOOM#4736",
"louieskouie#2469",
"LuisZabby#2618",
"Lukideluxe#4491",
"m145#0",
"m149#0",
"maedhros1978#0",
"majoneee#0",
"Malaya#2617",
"marfram#0",
"Mari#4091",
"mariachilocot#0",
"Mario Lafleur#9804",
"Marle#4641",
"marts6845#0",
"mathwiz100#0",
"mattholland#5596",
"mcfloatlover#0",
"Mecex#6833",
"MegaSkuci#3636",
"mel0nsoda#0",
"Melhk#4155",
"meltedplague856#0",
"mendion#0",
"mfrerck#0",
"micetro#0",
"Mickaël M.#2479",
"mikdagreat#0",
"mil0-#1281",
"minertyler100#0",
"mistec43#9728",
"moodeuce#0",
"MörköS#1433",
"morelando_#0",
"mqisie#0",
"mrfaq#0",
"MrShadow#0900",
"Muffyio#3282",
"Muunas#4096",
"mxyrk#1204",
"n0mori#6973",
"nack323#5273",
"NDDK#8648",
"NerDzzzzz#8658",
"neutrisicacid#0",
"Nevanator2005#7984",
"night#4546",
"nikvo#0",
"ninjaofninjas5#0",
"NNNNNNNNNNNNNN#2430",
"notleo._.#0",
"notzempro#0",
"odinn group mastubator#1009",
"offwo#7439",
"og_readmore#6535",
"oktopuse#8620",
"omenvoir#0",
"Oofie#4787",
"opaux#5052",
"Oscar._#6774",
"p1_carter#0",
"panquequeque#7897",
"Paul 楊#5532",
"peyton1996#0",
"pissarse#0972",
"pkric#0",
"PolloSalazar#1503",
"poopyoldhag#0",
"poteznymleczarz#0",
"PukPow#6394",
"pumpyheart#0",
"r3io4mf#0",
"r75mm#0",
"Red_309#2593",
"rens#5484",
"Reykon#3817",
"roguepotatobaduk#0",
"Rhubarb#1508",
"richardwolfvi#0",
"RIVAL | Ard#1561",
"rockdtben#0",
"romanplaysgames#8168",
"roncli#0",
"roryrorysupermarket#0",
"RyenwithanE#5674",
"sablen#2241",
"Sakurion#6289",
"salexm#0",
"SaltedSofa12#8996",
"SamoanGerman#2947",
"SARGIN#9722",
"scamper9#0",
"scoopman#0111",
"Semilogo777#0302",
"shackman04#0",
"shoppingtrolli#0",
"sidnev#0",
"sirmaser#0",
"sixfour#0130",
"skiplogic#9125",
"Slayer69#3183",
"sleebymaddy#0",
"Sleepy Samantha#8502",
"snowytetris#0",
"SodiumOverdose#8425",
"Somalian#9396",
"stolenshortsword#0",
"storminorman#0",
"suds1821#0",
"superjaycoder#0",
"Świdr#0486",
"tacomom18#0",
"teainrain#0",
"temphuibis#0",
"TetrisMasterRafał#0598",
"TetrisTime#8026",
"thatguywearingblue#7417",
"The1stNoel#0001",
"theianwright#0",
"thelovasman#0",
"TheMisterValor#1624",
"thisinthat#0",
"Threes > Twos#3333",
"thunderstorm281#0",
"thund7#0",
"timmykim915#0",
"TKK24#2514",
"TomelloSoulMan#7863",
"TotallyCalculatingPoet#8979",
"TotalRadNES#2445",
"trapzone707#0",
"treepriest#0",
"Tryad#0983",
"tugi#0",
"tweak_beacon#0",
"Twifty#3688",
"unor1ginalname#0",
"vachetbeasty#0",
"vandweller#7214",
"vanshtanwani#9639",
"Vernie#9671",
"w___i___d___e#0",
"weston6673#0",
"WhiteMonster#3552",
"wike#3985",
"winterra#0",
"XaeL#6732",
"xenoboots#0",
"XXBALT#9718",
"yeehawmckickass#0",
"Z Wing#6720",
"Zabby#2618",
"Zipley#7137",
"zxvye.#0",
"zydras07#0",
"ちどり#2119",
];

module.exports = {
  divisionData,
  adminRole,
  restreamerRole,
};
